# Generated by Django 4.1 on 2024-02-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture_url',
            new_name='profile_picture',
        ),
    ]
