# Generated by Django 4.1 on 2024-02-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkedge',
            unique_together={('from_user', 'to_user')},
        ),
    ]
