# Generated by Django 4.1 on 2024-03-02 18:21

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_postmedia_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.ImageField(upload_to=content.models.PostMedia.media_name),
        ),
    ]
